{
  lib,
  pkgs,
  config,
  ...
}:
let
  cfg = config.proxmox;

  cfgLine = name: value: ''
    ${name}: ${builtins.toString value}
  '';
  virtio0Storage = "local-lvm";
  cfgFile =
    fileName: properties:
    pkgs.writeTextDir fileName ''
      # generated by NixOS
      ${lib.concatStrings (lib.mapAttrsToList cfgLine properties)}
      #qmdump#map:scsi0:drive-scsi0:${virtio0Storage}:raw:
      #qmdump#map:efidisk0:drive-efidisk0:${virtio0Storage}:raw:
    '';

  vma = pkgs.francynox.proxmox-vma;

in
{
  proxmox = {
    qemuConf = {
      cores = 2;
      memory = 4096;
      bios = "ovmf";
      net0 = "virtio=00:00:00:00:00:00,bridge=vmbr0";
      virtio0 = "${virtio0Storage}:vm-9999-disk-0,discard=on,iothread=1,ssd=1";
    };
    qemuExtraConf = {
      cpu = "host";
      machine = "q35";
      numa = 1;
      efidisk0 = "${virtio0Storage}:vm-9999-disk-1,efitype=4m,size=4M";
    };
  };

  virtualisation.diskSize = 8192;

  boot = {
    loader.timeout = lib.mkForce 0;
    growPartition = lib.mkForce false;
  };

  fileSystems = {
    "/" = {
      fsType = lib.mkForce "tmpfs";
      device = lib.mkForce "tmpfs";
      autoResize = lib.mkForce false;
    };
    "/boot" = {
      device = lib.mkForce "/dev/disk/by-partlabel/disk-main-ESP";
    };
  };
  disko.devices.disk.main.imageSize = "8G";

  system.build.VMA = lib.mkForce (
    pkgs.runCommand "proxmox-vma-disko"
      {
        nativeBuildInputs = [
          vma
          pkgs.zstd
        ];
      }
      ''
        mkdir -p $out

        DISK_IMAGE="${config.system.build.diskoImages}/main.raw"

        if [ ! -f "$DISK_IMAGE" ]; then
           echo "Error: Disko image not found at $DISK_IMAGE"
           ls -R ${config.system.build.diskoImages}
           exit 1
        fi

        # Prepare EFI Vars
        cp ${pkgs.OVMF.fd}/FV/OVMF_VARS.fd EFI_VARS.fd
        chmod 644 EFI_VARS.fd
        truncate -s 4M EFI_VARS.fd

        # Change virtio0 to scsi0
        cp ${
          cfgFile "qemu-server.conf" (cfg.qemuConf // cfg.qemuExtraConf)
        }/qemu-server.conf ./qemu-server.conf
        sed -i 's/virtio0/scsi0/g' ./qemu-server.conf

        vma create "${config.image.baseName}.vma" \
          -c ./qemu-server.conf \
          -d format=raw:drive-scsi0="$DISK_IMAGE" \
          -d format=raw:drive-efidisk0=./EFI_VARS.fd

        zstd "${config.image.baseName}.vma"
        mv "${config.image.baseName}.vma.zst" $out/

        mkdir -p $out/nix-support
        echo "file vma $out/${config.image.baseName}.vma.zst" > $out/nix-support/hydra-build-products
      ''
  );
}
